export type Product = {
  id: string
  slug: string
  title: string
  price: string
  rating: string
  img: string
  images: string[]
  category: string
  badge?: string
  compareAt?: string
  shortDescription: string
  description: string
  features: string[]
  material?: string
  dimensions?: string
  sku: string
  reviewCount: number
  inStock: boolean
  stockCount?: number
  warranty?: string
  isNew?: boolean
  isLimited?: boolean
}

export type Category = {
  title: string
  slug: string
  count: string
  img: string
  size: 'large' | 'medium' | 'wide'
  description: string
}

export type LimitedProduct = {
  slug: string
  title: string
  price: string
  img: string
  units: string
  description: string
}

const catalog: Product[] = [
  {
    id: 'rx-001',
    slug: 'noir-ceramic-ritual-set',
    title: 'Noir Ceramic Ritual Set',
    price: '$148',
    rating: '4.9',
    img: 'https://images.unsplash.com/photo-1610701596007-11502861dcfa?w=700&q=80',
    images: [
      'https://images.unsplash.com/photo-1610701596007-11502861dcfa?w=900&q=80',
      'https://images.unsplash.com/photo-1616047006789-b7af5afb8c20?w=900&q=80',
      'https://images.unsplash.com/photo-1602874801006-1f7b6611c7e3?w=900&q=80',
    ],
    category: 'Home Essentials',
    badge: 'Best Seller',
    shortDescription: 'A matte-black ceramic trio for morning rituals and evening wind-down.',
    description: 'Crafted from high-fired stoneware with a satin matte glaze, the Noir Ceramic Ritual Set brings quiet luxury to your countertop. Includes a lidded jar, pour vessel, and tray — designed to coordinate with modern kitchens and spa-inspired bathrooms alike.',
    features: ['Hand-glazed stoneware', 'Dishwasher safe', 'Gift-ready packaging', 'Coordinates with Noir collection'],
    material: 'High-fired stoneware',
    dimensions: 'Tray 28 × 18 cm',
    sku: 'RX-HE-001',
    reviewCount: 284,
    inStock: true,
    warranty: '1 year craftsmanship guarantee',
  },
  {
    id: 'rx-002',
    slug: 'atelier-leather-carryall',
    title: 'Atelier Leather Carryall',
    price: '$286',
    rating: '4.8',
    img: 'https://images.unsplash.com/photo-1590874103328-eac38a683ce7?w=700&q=80',
    images: [
      'https://images.unsplash.com/photo-1590874103328-eac38a683ce7?w=900&q=80',
      'https://images.unsplash.com/photo-1548036328-c9fa89d128fa?w=900&q=80',
      'https://images.unsplash.com/photo-1627123424574-724758594e93?w=900&q=80',
    ],
    category: 'Travel Collection',
    badge: 'Top Rated',
    shortDescription: 'Full-grain leather weekender with reinforced handles and interior pockets.',
    description: 'Built for short escapes and daily commutes, the Atelier Leather Carryall combines supple full-grain leather with a structured silhouette. Interior dividers keep essentials organized; exterior zip pocket secures travel documents.',
    features: ['Full-grain vegetable-tanned leather', 'Removable shoulder strap', 'Interior zip pocket', 'Brass hardware'],
    material: 'Full-grain leather',
    dimensions: '42 × 28 × 18 cm',
    sku: 'RX-TC-002',
    reviewCount: 196,
    inStock: true,
    warranty: '2 year leather care guarantee',
  },
  {
    id: 'rx-003',
    slug: 'linen-lounge-throw',
    title: 'Linen Lounge Throw',
    price: '$124',
    rating: '4.9',
    img: 'https://images.unsplash.com/photo-1583845112203-29329902330b?w=700&q=80',
    images: [
      'https://images.unsplash.com/photo-1583845112203-29329902330b?w=900&q=80',
      'https://images.unsplash.com/photo-1584100936595-c0654b55a2e2?w=900&q=80',
      'https://images.unsplash.com/photo-1615874694520-474822394e73?w=900&q=80',
    ],
    category: 'Home Essentials',
    badge: 'Best Seller',
    shortDescription: 'Stone-washed European linen throw with a relaxed drape and breathable weave.',
    description: 'Woven from Belgian flax and stone-washed for softness from day one. The Linen Lounge Throw layers beautifully on sofas and beds, offering year-round comfort with a naturally textured finish that improves with every wash.',
    features: ['100% European flax linen', 'Pre-washed for softness', 'OEKO-TEX certified dyes', 'Machine washable'],
    material: 'Belgian flax linen',
    dimensions: '150 × 200 cm',
    sku: 'RX-HE-003',
    reviewCount: 312,
    inStock: true,
  },
  {
    id: 'rx-004',
    slug: 'brushed-gold-tray',
    title: 'Brushed Gold Tray',
    price: '$96',
    rating: '5.0',
    img: 'https://images.unsplash.com/photo-1602874801006-1f7b6611c7e3?w=700&q=80',
    images: [
      'https://images.unsplash.com/photo-1602874801006-1f7b6611c7e3?w=900&q=80',
      'https://images.unsplash.com/photo-1615529328331-f8917597711f?w=900&q=80',
    ],
    category: 'Lifestyle Collection',
    badge: 'New',
    isNew: true,
    shortDescription: 'Brushed brass vanity tray for jewelry, candles, and curated vignettes.',
    description: 'A sculptural accent piece finished in brushed gold-tone brass. Use it to corral everyday objects on a dresser, coffee table, or entryway — the subtle sheen catches light without overpowering your space.',
    features: ['Brushed brass finish', 'Felt base protects surfaces', 'Tarnish-resistant coating', 'Hand-finished edges'],
    material: 'Brass with protective coating',
    dimensions: '32 × 18 × 3 cm',
    sku: 'RX-LC-004',
    reviewCount: 87,
    inStock: true,
  },
  {
    id: 'rx-005',
    slug: 'stonewashed-linen-set',
    title: 'Stonewashed Linen Set',
    price: '$168',
    rating: '4.9',
    img: 'https://images.unsplash.com/photo-1615874694520-474822394e73?w=700&q=80',
    images: [
      'https://images.unsplash.com/photo-1615874694520-474822394e73?w=900&q=80',
      'https://images.unsplash.com/photo-1583845112203-29329902330b?w=900&q=80',
    ],
    category: 'Home Essentials',
    badge: 'New Season',
    isNew: true,
    shortDescription: 'Four-piece linen bedding set in a calming neutral palette.',
    description: 'Elevate your bedroom with stonewashed linen that feels lived-in from the first night. Set includes duvet cover, two pillowcases, and a fitted sheet — all designed for breathability and a relaxed, hotel-quality drape.',
    features: ['100% stonewashed linen', 'Envelope closure pillowcases', 'Deep-pocket fitted sheet', 'Gets softer over time'],
    material: 'European linen',
    dimensions: 'Queen size set',
    sku: 'RX-HE-005',
    reviewCount: 143,
    inStock: true,
  },
  {
    id: 'rx-006',
    slug: 'smoked-glass-vessel',
    title: 'Smoked Glass Vessel',
    price: '$82',
    rating: '4.7',
    img: 'https://images.unsplash.com/photo-1616047006789-b7af5afb8c20?w=700&q=80',
    images: [
      'https://images.unsplash.com/photo-1616047006789-b7af5afb8c20?w=900&q=80',
      'https://images.unsplash.com/photo-1603006905004-6a8d7c8f3f0e?w=900&q=80',
    ],
    category: 'Home Essentials',
    badge: 'New Season',
    isNew: true,
    shortDescription: 'Hand-blown smoked glass vase with a tapered silhouette.',
    description: 'Each vessel is mouth-blown by artisans, giving every piece subtle variations in tone and form. The smoked finish adds depth and pairs effortlessly with dried botanicals, fresh stems, or as a standalone sculptural object.',
    features: ['Mouth-blown glass', 'Unique artisan variations', 'Wide stable base', 'Indoor display piece'],
    material: 'Hand-blown glass',
    dimensions: 'H 24 cm × Ø 12 cm',
    sku: 'RX-HE-006',
    reviewCount: 76,
    inStock: true,
  },
  {
    id: 'rx-007',
    slug: 'soft-grain-card-holder',
    title: 'Soft Grain Card Holder',
    price: '$74',
    rating: '4.8',
    img: 'https://images.unsplash.com/photo-1627123424574-724758594e93?w=700&q=80',
    images: [
      'https://images.unsplash.com/photo-1627123424574-724758594e93?w=900&q=80',
    ],
    category: 'Luxury Accessories',
    badge: 'New Season',
    isNew: true,
    shortDescription: 'Slim leather card case with six slots and a central pocket.',
    description: 'Minimalist carry for cards and folded notes. Soft-grain leather develops a rich patina over time, while precise stitching and a reinforced spine keep the profile slim enough for any pocket.',
    features: ['6 card slots + center pocket', 'Develops natural patina', 'RFID lining optional', 'Gift box included'],
    material: 'Soft-grain calfskin leather',
    dimensions: '10 × 7.5 cm',
    sku: 'RX-LA-007',
    reviewCount: 118,
    inStock: true,
  },
  {
    id: 'rx-008',
    slug: 'minimal-desk-object',
    title: 'Minimal Desk Object',
    price: '$118',
    rating: '4.9',
    img: 'https://images.unsplash.com/photo-1518005020951-eccb494ad742?w=700&q=80',
    images: [
      'https://images.unsplash.com/photo-1518005020951-eccb494ad742?w=900&q=80',
      'https://images.unsplash.com/photo-1524758631624-e2822e304c36?w=900&q=80',
    ],
    category: 'Lifestyle Collection',
    badge: 'New Season',
    isNew: true,
    shortDescription: 'Sculptural concrete and oak desk organizer for pens and small essentials.',
    description: 'A study in balance — cast concrete base meets warm oak dividers. Keeps your workspace intentional without visual clutter. Ideal for pens, phone, keys, and the small objects that deserve a proper home.',
    features: ['Cast concrete + oak', 'Non-slip base pad', 'Three compartment layout', 'Architectural silhouette'],
    material: 'Concrete and European oak',
    dimensions: '22 × 8 × 6 cm',
    sku: 'RX-LC-008',
    reviewCount: 64,
    inStock: true,
  },
  {
    id: 'rx-009',
    slug: 'brushed-brass-tray',
    title: 'Brushed Brass Tray',
    price: '$96',
    rating: '4.8',
    img: 'https://images.unsplash.com/photo-1615529328331-f8917597711f?w=700&q=80',
    images: [
      'https://images.unsplash.com/photo-1615529328331-f8917597711f?w=900&q=80',
      'https://images.unsplash.com/photo-1602874801006-1f7b6611c7e3?w=900&q=80',
    ],
    category: 'Home Essentials',
    badge: 'Sale',
    compareAt: '$128',
    shortDescription: 'Round brass serving tray with raised lip and brushed finish.',
    description: 'From breakfast in bed to evening aperitifs, this brushed brass tray adds warmth to every ritual. Raised edges keep items secure; the hand-brushed surface resists fingerprints and develops character over time.',
    features: ['Raised edge design', 'Anti-fingerprint finish', 'Food-safe coating', 'Leather handle inserts'],
    material: 'Brushed brass',
    dimensions: 'Ø 38 cm',
    sku: 'RX-HE-009',
    reviewCount: 201,
    inStock: true,
  },
  {
    id: 'rx-010',
    slug: 'woven-throw-blanket',
    title: 'Woven Throw Blanket',
    price: '$142',
    rating: '4.9',
    img: 'https://images.unsplash.com/photo-1584100936595-c0654b55a2e2?w=700&q=80',
    images: [
      'https://images.unsplash.com/photo-1584100936595-c0654b55a2e2?w=900&q=80',
      'https://images.unsplash.com/photo-1583845112203-29329902330b?w=900&q=80',
    ],
    category: 'Home Essentials',
    shortDescription: 'Cotton-wool blend throw with a textured herringbone weave.',
    description: 'Soft enough for lounging, structured enough to drape with intention. The herringbone weave adds visual interest while the cotton-wool blend regulates temperature through every season.',
    features: ['Cotton-wool blend', 'Herringbone weave', 'Fringed edges', 'Dry clean or gentle wash'],
    material: '80% cotton, 20% wool',
    dimensions: '130 × 170 cm',
    sku: 'RX-HE-010',
    reviewCount: 167,
    inStock: true,
  },
  {
    id: 'rx-011',
    slug: 'wireless-charging-dock',
    title: 'Wireless Charging Dock',
    price: '$89',
    rating: '4.6',
    img: 'https://images.unsplash.com/photo-1591290619762-d2a4a8a2d06e?w=700&q=80',
    images: [
      'https://images.unsplash.com/photo-1591290619762-d2a4a8a2d06e?w=900&q=80',
      'https://images.unsplash.com/photo-1526170375885-4d8ecf77b99f?w=900&q=80',
    ],
    category: 'Smart Technology',
    shortDescription: 'Dual-device charging stand in matte aluminum with fast-charge support.',
    description: 'Charge your phone and earbuds simultaneously on a single sculpted dock. Matte aluminum construction stays cool under load; weighted base prevents tipping. Compatible with Qi-enabled devices.',
    features: ['15W fast wireless charging', 'Dual-device support', 'Matte aluminum body', 'Cable management channel'],
    material: 'Anodized aluminum',
    dimensions: '12 × 8 × 10 cm',
    sku: 'RX-ST-011',
    reviewCount: 93,
    inStock: true,
    warranty: '1 year electronics warranty',
  },
  {
    id: 'rx-012',
    slug: 'premium-weekender-bag',
    title: 'Premium Weekender Bag',
    price: '$312',
    rating: '4.9',
    img: 'https://images.unsplash.com/photo-1548036328-c9fa89d128fa?w=700&q=80',
    images: [
      'https://images.unsplash.com/photo-1548036328-c9fa89d128fa?w=900&q=80',
      'https://images.unsplash.com/photo-1590874103328-eac38a683ce7?w=900&q=80',
    ],
    category: 'Travel Collection',
    badge: 'New',
    isNew: true,
    shortDescription: 'Water-resistant canvas weekender with leather trim and shoe compartment.',
    description: 'Designed for 48-hour trips, this weekender fits overhead compartments while offering surprising capacity. Dedicated shoe pocket, laptop sleeve, and trolley sleeve make it the most functional bag in our travel edit.',
    features: ['Water-resistant canvas', 'Separate shoe compartment', 'Trolley sleeve', 'Padded laptop sleeve'],
    material: 'Waxed canvas + leather trim',
    dimensions: '50 × 28 × 25 cm',
    sku: 'RX-TC-012',
    reviewCount: 154,
    inStock: true,
    warranty: '2 year craftsmanship guarantee',
  },
  {
    id: 'rx-013',
    slug: 'marble-coaster-set',
    title: 'Marble Coaster Set',
    price: '$58',
    rating: '4.7',
    img: 'https://images.unsplash.com/photo-1602874801006-1f7b6611c7e3?w=700&q=80',
    images: [
      'https://images.unsplash.com/photo-1602874801006-1f7b6611c7e3?w=900&q=80',
    ],
    category: 'Lifestyle Collection',
    shortDescription: 'Set of four Carrara marble coasters with cork backing.',
    description: 'Each coaster is cut from genuine Carrara marble, so no two sets are exactly alike. Cork backing protects tabletops and silences glass placement — a small detail that makes everyday entertaining feel considered.',
    features: ['Genuine Carrara marble', 'Cork non-slip backing', 'Set of four', 'Natural stone variation'],
    material: 'Carrara marble + cork',
    dimensions: 'Ø 10 cm each',
    sku: 'RX-LC-013',
    reviewCount: 89,
    inStock: true,
  },
  {
    id: 'rx-014',
    slug: 'silk-sleep-mask',
    title: 'Silk Sleep Mask',
    price: '$48',
    rating: '4.8',
    img: 'https://images.unsplash.com/photo-1556228720-195a672e8a03?w=700&q=80',
    images: [
      'https://images.unsplash.com/photo-1556228720-195a672e8a03?w=900&q=80',
    ],
    category: 'Luxury Accessories',
    shortDescription: '22-momme mulberry silk mask with adjustable strap.',
    description: 'Gentle on skin and hair, our silk sleep mask blocks light without pressure. Mulberry silk regulates temperature and the wide elastic strap adjusts silently — ideal for travel and deep rest at home.',
    features: ['22-momme mulberry silk', 'Adjustable wide strap', 'Skin and hair friendly', 'Includes travel pouch'],
    material: '100% mulberry silk',
    sku: 'RX-LA-014',
    reviewCount: 234,
    inStock: true,
  },
  {
    id: 'rx-015',
    slug: 'scented-candle-trio',
    title: 'Scented Candle Trio',
    price: '$72',
    rating: '4.9',
    img: 'https://images.unsplash.com/photo-1603006905004-6a8d7c8f3f0e?w=700&q=80',
    images: [
      'https://images.unsplash.com/photo-1603006905004-6a8d7c8f3f0e?w=900&q=80',
      'https://images.unsplash.com/photo-1616047006789-b7af5afb8c20?w=900&q=80',
    ],
    category: 'Home Essentials',
    badge: 'Best Seller',
    shortDescription: 'Three hand-poured soy candles in Cedar, Bergamot, and Vetiver.',
    description: 'Each candle is hand-poured with a cotton wick and clean-burning soy wax. The trio covers morning clarity, afternoon calm, and evening warmth — presented in reusable matte glass vessels.',
    features: ['Clean-burning soy wax', '40-hour burn per candle', 'Reusable glass vessels', 'Gift box packaging'],
    material: 'Soy wax, cotton wick',
    dimensions: '3 × 200g candles',
    sku: 'RX-HE-015',
    reviewCount: 278,
    inStock: true,
  },
  {
    id: 'rx-016',
    slug: 'leather-passport-wallet',
    title: 'Leather Passport Wallet',
    price: '$64',
    rating: '4.8',
    img: 'https://images.unsplash.com/photo-1627123424574-724758594e93?w=700&q=80',
    images: [
      'https://images.unsplash.com/photo-1627123424574-724758594e93?w=900&q=80',
    ],
    category: 'Travel Collection',
    shortDescription: 'Bifold passport holder with boarding pass slot and card pockets.',
    description: 'Keep travel documents together in one refined folio. Holds passport, boarding passes, and up to four cards — slim enough for a jacket pocket, durable enough for years of departures.',
    features: ['4 card slots', 'Boarding pass pocket', 'Slim bifold profile', 'Develops leather patina'],
    material: 'Vegetable-tanned leather',
    dimensions: '14 × 10 cm',
    sku: 'RX-TC-016',
    reviewCount: 145,
    inStock: true,
  },
  {
    id: 'rx-017',
    slug: 'cashmere-wrap-scarf',
    title: 'Cashmere Wrap Scarf',
    price: '$198',
    rating: '4.9',
    img: 'https://images.unsplash.com/photo-1520903920353-86db920bc4a1?w=700&q=80',
    images: [
      'https://images.unsplash.com/photo-1520903920353-86db920bc4a1?w=900&q=80',
    ],
    category: 'Luxury Accessories',
    badge: 'New',
    isNew: true,
    shortDescription: 'Ultra-fine Grade A cashmere wrap in a versatile oversized cut.',
    description: 'Spun from Grade A Mongolian cashmere, this wrap is featherlight yet insulating. The oversized dimensions allow styling as a scarf, shawl, or travel blanket — a timeless piece that elevates any outfit.',
    features: ['Grade A Mongolian cashmere', 'Oversized wrap cut', 'Hand-finished fringe', 'Comes in gift box'],
    material: '100% cashmere',
    dimensions: '200 × 70 cm',
    sku: 'RX-LA-017',
    reviewCount: 67,
    inStock: true,
  },
  {
    id: 'rx-018',
    slug: 'smart-speaker-hub',
    title: 'Smart Speaker Hub',
    price: '$159',
    rating: '4.5',
    img: 'https://images.unsplash.com/photo-1545454675-3531b543be5d?w=700&q=80',
    images: [
      'https://images.unsplash.com/photo-1545454675-3531b543be5d?w=900&q=80',
      'https://images.unsplash.com/photo-1526170375885-4d8ecf77b99f?w=900&q=80',
    ],
    category: 'Smart Technology',
    shortDescription: 'Room-filling speaker with voice assistant and multi-room pairing.',
    description: 'Premium audio meets intelligent home control. The Smart Speaker Hub delivers 360° sound, responds to voice commands, and pairs with additional units for whole-home audio. Fabric-wrapped design blends into any interior.',
    features: ['360° room-filling sound', 'Voice assistant built-in', 'Multi-room pairing', 'Wi-Fi and Bluetooth'],
    material: 'Fabric-wrapped enclosure',
    dimensions: 'Ø 12 × H 18 cm',
    sku: 'RX-ST-018',
    reviewCount: 112,
    inStock: true,
    warranty: '2 year electronics warranty',
  },
  {
    id: 'rx-019',
    slug: 'ceramic-pour-over-set',
    title: 'Ceramic Pour-Over Set',
    price: '$112',
    rating: '4.8',
    img: 'https://images.unsplash.com/photo-1495474472287-4d71bcdd2085?w=700&q=80',
    images: [
      'https://images.unsplash.com/photo-1495474472287-4d71bcdd2085?w=900&q=80',
    ],
    category: 'Home Essentials',
    shortDescription: 'Handmade ceramic dripper, carafe, and scoop for ritual coffee brewing.',
    description: 'Slow mornings deserve better coffee. This pour-over set includes a V60-style dripper, matching carafe, and bamboo scoop — all in a cohesive glaze palette designed for countertop display.',
    features: ['Handmade ceramic', 'Heat-retaining carafe', 'Bamboo scoop included', 'Dishwasher safe dripper'],
    material: 'Glazed ceramic + bamboo',
    dimensions: 'Carafe 600ml capacity',
    sku: 'RX-HE-019',
    reviewCount: 98,
    inStock: true,
  },
  {
    id: 'rx-020',
    slug: 'leather-tech-organizer',
    title: 'Leather Tech Organizer',
    price: '$134',
    rating: '4.7',
    img: 'https://images.unsplash.com/photo-1526170375885-4d8ecf77b99f?w=700&q=80',
    images: [
      'https://images.unsplash.com/photo-1526170375885-4d8ecf77b99f?w=900&q=80',
    ],
    category: 'Smart Technology',
    shortDescription: 'Zippered leather pouch for cables, chargers, and travel tech.',
    description: 'End cable chaos with a leather organizer that feels as good as it functions. Elastic loops, mesh pockets, and a padded main compartment protect your tech essentials in transit.',
    features: ['Elastic cable loops', 'Mesh accessory pockets', 'YKK zip closure', 'Fits in carry-on'],
    material: 'Pebbled leather',
    dimensions: '24 × 16 × 5 cm',
    sku: 'RX-ST-020',
    reviewCount: 81,
    inStock: true,
  },
  {
    id: 'rx-021',
    slug: 'hard-shell-carry-on',
    title: 'Hard Shell Carry-On',
    price: '$348',
    rating: '4.8',
    img: 'https://images.unsplash.com/photo-1565026057447-bc90a3dceb87?w=700&q=80',
    images: [
      'https://images.unsplash.com/photo-1565026057447-bc90a3dceb87?w=900&q=80',
    ],
    category: 'Travel Collection',
    shortDescription: 'Lightweight polycarbonate carry-on with 360° spinner wheels.',
    description: 'Engineered for frequent flyers — ultralight polycarbonate shell, TSA-approved lock, and whisper-quiet spinner wheels. Interior compression system maximizes packing space within airline carry-on limits.',
    features: ['TSA-approved lock', '360° spinner wheels', 'Interior compression straps', 'Airline carry-on size'],
    material: 'Polycarbonate shell',
    dimensions: '55 × 38 × 23 cm',
    sku: 'RX-TC-021',
    reviewCount: 176,
    inStock: true,
    warranty: '5 year shell warranty',
  },
  {
    id: 'rx-022',
    slug: 'walnut-serving-board',
    title: 'Walnut Serving Board',
    price: '$88',
    rating: '4.9',
    img: 'https://images.unsplash.com/photo-1607623489235-3b301b9b662b?w=700&q=80',
    images: [
      'https://images.unsplash.com/photo-1607623489235-3b301b9b662b?w=900&q=80',
    ],
    category: 'Lifestyle Collection',
    shortDescription: 'Single-slab American walnut board with juice groove and handle cutout.',
    description: 'From charcuterie spreads to everyday slicing, this walnut board is a kitchen heirloom in the making. Food-safe oil finish enhances the grain; integrated juice groove keeps countertops clean.',
    features: ['Single-slab American walnut', 'Juice groove channel', 'Food-safe oil finish', 'Handle cutout'],
    material: 'American black walnut',
    dimensions: '45 × 28 × 2 cm',
    sku: 'RX-LC-022',
    reviewCount: 132,
    inStock: true,
  },
  {
    id: 'rx-023',
    slug: 'noise-canceling-earbuds',
    title: 'Noise-Canceling Earbuds',
    price: '$179',
    rating: '4.7',
    img: 'https://images.unsplash.com/photo-1590658268037-6bf12165a8df?w=700&q=80',
    images: [
      'https://images.unsplash.com/photo-1590658268037-6bf12165a8df?w=900&q=80',
    ],
    category: 'Smart Technology',
    badge: 'Top Rated',
    shortDescription: 'True wireless earbuds with adaptive ANC and 32-hour total battery.',
    description: 'Immersive sound with adaptive noise cancellation that adjusts to your environment. Six-hour earbuds battery, 26-hour charging case, and IPX5 water resistance for workouts and commutes.',
    features: ['Adaptive noise cancellation', '32-hour total battery', 'IPX5 water resistant', 'Touch controls'],
    sku: 'RX-ST-023',
    reviewCount: 289,
    inStock: true,
    warranty: '1 year electronics warranty',
  },
  {
    id: 'rx-024',
    slug: 'sterling-cufflinks',
    title: 'Sterling Cufflinks',
    price: '$156',
    rating: '4.9',
    img: 'https://images.unsplash.com/photo-1611591437281-460bfbe1220a?w=700&q=80',
    images: [
      'https://images.unsplash.com/photo-1611591437281-460bfbe1220a?w=900&q=80',
    ],
    category: 'Luxury Accessories',
    shortDescription: 'Hand-polished sterling silver cufflinks with toggle closure.',
    description: 'Understated elegance for formal occasions and sharp everyday dressing. Each pair is hand-polished to a mirror finish and arrives in a velvet-lined presentation box.',
    features: ['925 sterling silver', 'Toggle-back closure', 'Hand-polished finish', 'Velvet presentation box'],
    material: '925 sterling silver',
    sku: 'RX-LA-024',
    reviewCount: 54,
    inStock: true,
  },
  {
    id: 'rx-025',
    slug: 'packing-cube-set',
    title: 'Packing Cube Set',
    price: '$68',
    rating: '4.6',
    img: 'https://images.unsplash.com/photo-1553062407-98eeb64c6a62?w=700&q=80',
    images: [
      'https://images.unsplash.com/photo-1553062407-98eeb64c6a62?w=900&q=80',
    ],
    category: 'Travel Collection',
    shortDescription: 'Set of three compression packing cubes in water-resistant nylon.',
    description: 'Organize your suitcase like a pro. Three graduated sizes with compression zippers fit more while keeping clothes wrinkle-free. Mesh tops let you see contents at a glance.',
    features: ['3 graduated sizes', 'Compression zippers', 'Mesh visibility panels', 'Water-resistant nylon'],
    material: 'Ripstop nylon',
    sku: 'RX-TC-025',
    reviewCount: 203,
    inStock: true,
  },
  {
    id: 'rx-026',
    slug: 'hand-blown-wine-glasses',
    title: 'Hand-Blown Wine Glasses',
    price: '$94',
    rating: '4.8',
    img: 'https://images.unsplash.com/photo-1510812431400-5747704b07e3?w=700&q=80',
    images: [
      'https://images.unsplash.com/photo-1510812431400-5747704b07e3?w=900&q=80',
    ],
    category: 'Lifestyle Collection',
    shortDescription: 'Set of four hand-blown crystal wine glasses with fine rim.',
    description: 'Thin, featherlight rims enhance every sip. Hand-blown from lead-free crystal, each glass has subtle variations that speak to artisan craftsmanship. Set of four in a protective gift box.',
    features: ['Lead-free crystal', 'Hand-blown artisan glass', 'Ultra-thin rim', 'Set of four'],
    material: 'Lead-free crystal',
    dimensions: '480ml capacity each',
    sku: 'RX-LC-026',
    reviewCount: 91,
    inStock: true,
  },
  {
    id: 'rx-027',
    slug: 'smart-desk-lamp',
    title: 'Smart Desk Lamp',
    price: '$124',
    rating: '4.7',
    img: 'https://images.unsplash.com/photo-1507473885765-e6ed057f782c?w=700&q=80',
    images: [
      'https://images.unsplash.com/photo-1507473885765-e6ed057f782c?w=900&q=80',
    ],
    category: 'Smart Technology',
    isNew: true,
    badge: 'New',
    shortDescription: 'Adjustable LED desk lamp with app control and circadian modes.',
    description: 'Light that adapts to your day. Five color temperatures, dimming via touch or app, and a focused beam that reduces eye strain. Minimal aluminum arm with a weighted base for stability.',
    features: ['5 color temperature modes', 'App and touch control', 'Circadian scheduling', 'USB charging port'],
    material: 'Aluminum + steel base',
    sku: 'RX-ST-027',
    reviewCount: 73,
    inStock: true,
    warranty: '2 year electronics warranty',
  },
  {
    id: 'rx-028',
    slug: 'merino-travel-wrap',
    title: 'Merino Travel Wrap',
    price: '$108',
    rating: '4.8',
    img: 'https://images.unsplash.com/photo-1434389677669-e08b4cac3105?w=700&q=80',
    images: [
      'https://images.unsplash.com/photo-1434389677669-e08b4cac3105?w=900&q=80',
    ],
    category: 'Travel Collection',
    shortDescription: 'Lightweight merino wool wrap that packs small and layers warm.',
    description: 'The ultimate travel companion — breathable merino wool regulates temperature on planes, in hotels, and everywhere between. Packs to the size of a paperback and resists odor naturally.',
    features: ['Australian merino wool', 'Odor-resistant fibers', 'Packs to pocket size', 'Machine washable'],
    material: '100% merino wool',
    dimensions: '180 × 60 cm',
    sku: 'RX-TC-028',
    reviewCount: 119,
    inStock: true,
  },
  {
    id: 'rx-029',
    slug: 'obsidian-signature-box',
    title: 'Obsidian Signature Box',
    price: '$320',
    rating: '5.0',
    img: 'https://images.unsplash.com/photo-1604014237800-1c9102c219da?w=700&q=80',
    images: [
      'https://images.unsplash.com/photo-1604014237800-1c9102c219da?w=900&q=80',
    ],
    category: 'Exclusive Editions',
    badge: 'Limited',
    isLimited: true,
    shortDescription: 'Limited-edition lacquer gift box with curated home essentials inside.',
    description: 'Numbered edition of 200. The Obsidian Signature Box opens to reveal four hand-selected home essentials — candle, tray, vessel, and linen square — in a deep lacquer presentation case.',
    features: ['Numbered edition of 200', 'Four curated essentials inside', 'Lacquer presentation case', 'Certificate of authenticity'],
    sku: 'RX-EE-029',
    reviewCount: 42,
    inStock: true,
    stockCount: 24,
  },
  {
    id: 'rx-030',
    slug: 'heritage-leather-folio',
    title: 'Heritage Leather Folio',
    price: '$245',
    rating: '4.9',
    img: 'https://images.unsplash.com/photo-1627123424574-724758594e93?w=700&q=80',
    images: [
      'https://images.unsplash.com/photo-1627123424574-724758594e93?w=900&q=80',
    ],
    category: 'Exclusive Editions',
    badge: 'Limited',
    isLimited: true,
    shortDescription: 'Heritage leather document folio with hand-stitched spine.',
    description: 'A collector piece for the discerning professional. Heritage leather, hand-stitched spine, and suede-lined interior protect documents and tablets up to 13 inches. Edition of 150.',
    features: ['Heritage leather exterior', 'Hand-stitched spine', 'Suede-lined interior', 'Edition of 150'],
    material: 'Heritage leather',
    sku: 'RX-EE-030',
    reviewCount: 28,
    inStock: true,
    stockCount: 18,
  },
  {
    id: 'rx-031',
    slug: 'artisan-crystal-decanter',
    title: 'Artisan Crystal Decanter',
    price: '$198',
    rating: '4.9',
    img: 'https://images.unsplash.com/photo-1616047006789-b7af5afb8c20?w=700&q=80',
    images: [
      'https://images.unsplash.com/photo-1616047006789-b7af5afb8c20?w=900&q=80',
    ],
    category: 'Exclusive Editions',
    badge: 'Limited',
    isLimited: true,
    shortDescription: 'Hand-cut crystal decanter with matching stopper, edition of 100.',
    description: 'Cut by master glass artisans, each decanter refracts light through precise facets. Includes a fitted stopper and arrives in a wooden presentation crate. A centerpiece for the home bar.',
    features: ['Hand-cut lead-free crystal', 'Matching fitted stopper', 'Wooden presentation crate', 'Edition of 100'],
    material: 'Hand-cut crystal',
    dimensions: '750ml capacity',
    sku: 'RX-EE-031',
    reviewCount: 36,
    inStock: true,
    stockCount: 12,
  },
  {
    id: 'rx-032',
    slug: 'linen-table-runner',
    title: 'Linen Table Runner',
    price: '$54',
    rating: '4.7',
    img: 'https://images.unsplash.com/photo-1616486338812-3dadae4b4ace?w=700&q=80',
    images: [
      'https://images.unsplash.com/photo-1616486338812-3dadae4b4ace?w=900&q=80',
    ],
    category: 'Home Essentials',
    shortDescription: 'Stonewashed linen runner with mitered corners for dining tables.',
    description: 'Instantly elevates any table setting. Stonewashed for a relaxed texture, with mitered corners that lie flat and a neutral tone that complements any dinnerware collection.',
    features: ['Stonewashed linen', 'Mitered corners', 'Neutral tone palette', 'Machine washable'],
    material: 'European linen',
    dimensions: '45 × 250 cm',
    sku: 'RX-HE-032',
    reviewCount: 58,
    inStock: true,
  },
  {
    id: 'rx-033',
    slug: 'titanium-writing-pen',
    title: 'Titanium Writing Pen',
    price: '$142',
    rating: '4.8',
    img: 'https://images.unsplash.com/photo-1583485088034-697a5b048cc0?w=700&q=80',
    images: [
      'https://images.unsplash.com/photo-1583485088034-697a5b048cc0?w=900&q=80',
    ],
    category: 'Luxury Accessories',
    shortDescription: 'Machined titanium rollerball pen with knurled grip.',
    description: 'Precision-machined from grade 5 titanium with a knurled grip section for confident writing. Accepts standard rollerball refills; presented in an aluminum tube case.',
    features: ['Grade 5 titanium body', 'Knurled grip section', 'Standard refill compatible', 'Aluminum tube case'],
    material: 'Grade 5 titanium',
    sku: 'RX-LA-033',
    reviewCount: 47,
    inStock: true,
  },
  {
    id: 'rx-034',
    slug: 'bamboo-bath-caddy',
    title: 'Bamboo Bath Caddy',
    price: '$78',
    rating: '4.6',
    img: 'https://images.unsplash.com/photo-1600334089648-b0d9d3028eb2?w=700&q=80',
    images: [
      'https://images.unsplash.com/photo-1600334089648-b0d9d3028eb2?w=900&q=80',
    ],
    category: 'Home Essentials',
    shortDescription: 'Expandable bamboo bath tray with book stand and wine holder.',
    description: 'Transform bath time into a ritual. Expandable bamboo caddy spans most tub widths, with slots for a book, wine glass, candle, and phone — all finished with a water-resistant coating.',
    features: ['Expandable 72–95 cm span', 'Integrated wine glass holder', 'Book/tablet stand', 'Water-resistant coating'],
    material: 'Sustainable bamboo',
    sku: 'RX-HE-034',
    reviewCount: 164,
    inStock: true,
  },
  {
    id: 'rx-035',
    slug: 'architect-desk-lamp',
    title: 'Architect Desk Lamp',
    price: '$168',
    rating: '4.8',
    img: 'https://images.unsplash.com/photo-1513506003901-1e6a229e2d15?w=700&q=80',
    images: [
      'https://images.unsplash.com/photo-1513506003901-1e6a229e2d15?w=900&q=80',
    ],
    category: 'Lifestyle Collection',
    shortDescription: 'Adjustable brass architect lamp with articulating arm.',
    description: 'Inspired by classic drafting studios, this architect lamp features an articulating brass arm, weighted base, and focused beam. A statement piece that works as hard as it looks.',
    features: ['Articulating brass arm', 'Weighted stable base', 'Focused task beam', 'Inline dimmer switch'],
    material: 'Brass + steel',
    sku: 'RX-LC-035',
    reviewCount: 86,
    inStock: true,
  },
  {
    id: 'rx-036',
    slug: 'midnight-edition-watch-roll',
    title: 'Midnight Edition Watch Roll',
    price: '$275',
    rating: '5.0',
    img: 'https://images.unsplash.com/photo-1523170335258-f5ed11844a48?w=700&q=80',
    images: [
      'https://images.unsplash.com/photo-1523170335258-f5ed11844a48?w=900&q=80',
    ],
    category: 'Exclusive Editions',
    badge: 'Limited',
    isLimited: true,
    shortDescription: 'Three-slot suede watch roll in midnight navy, numbered edition.',
    description: 'Protect your timepieces in supple suede with individual cushioned slots. The Midnight Edition features contrast stitching, a snap closure, and numbered authenticity card. Edition of 75.',
    features: ['3 cushioned watch slots', 'Supple suede interior', 'Numbered authenticity card', 'Edition of 75'],
    material: 'Navy leather + suede',
    sku: 'RX-EE-036',
    reviewCount: 19,
    inStock: true,
    stockCount: 8,
  },
]

export const allProducts: Product[] = catalog

export const bestSellers: Product[] = catalog.filter((p) =>
  ['Best Seller', 'Top Rated'].includes(p.badge ?? '')
).slice(0, 4)

export const newArrivals: Product[] = catalog.filter((p) => p.isNew).slice(0, 8)

export const limitedProducts: LimitedProduct[] = catalog
  .filter((p) => p.isLimited)
  .map((p) => ({
    slug: p.slug,
    title: p.title,
    price: p.price,
    img: p.img,
    units: p.stockCount ? `Only ${p.stockCount} left` : 'Limited stock',
    description: p.shortDescription,
  }))

function countByCategory(name: string) {
  const count = catalog.filter((p) => p.category === name).length
  return `${count} piece${count !== 1 ? 's' : ''}`
}

export const categories: Category[] = [
  {
    title: 'Luxury Accessories',
    slug: 'luxury-accessories',
    count: countByCategory('Luxury Accessories'),
    img: 'https://images.unsplash.com/photo-1627123424574-724758594e93?w=800&q=80',
    size: 'large',
    description: 'Refined leather goods, silk essentials, and sterling accents for everyday elegance.',
  },
  {
    title: 'Home Essentials',
    slug: 'home-essentials',
    count: countByCategory('Home Essentials'),
    img: 'https://images.unsplash.com/photo-1615874694520-474822394e73?w=700&q=80',
    size: 'medium',
    description: 'Linen bedding, ceramic rituals, candles, and objects that make home feel intentional.',
  },
  {
    title: 'Smart Technology',
    slug: 'smart-technology',
    count: countByCategory('Smart Technology'),
    img: 'https://images.unsplash.com/photo-1526170375885-4d8ecf77b99f?w=700&q=80',
    size: 'medium',
    description: 'Thoughtfully designed tech that blends into your space — audio, charging, and lighting.',
  },
  {
    title: 'Travel Collection',
    slug: 'travel-collection',
    count: countByCategory('Travel Collection'),
    img: 'https://images.unsplash.com/photo-1590874103328-eac38a683ce7?w=800&q=80',
    size: 'large',
    description: 'Weekenders, organizers, and carry-on essentials built for departures and returns.',
  },
  {
    title: 'Lifestyle Collection',
    slug: 'lifestyle-collection',
    count: countByCategory('Lifestyle Collection'),
    img: 'https://images.unsplash.com/photo-1524758631624-e2822e304c36?w=700&q=80',
    size: 'medium',
    description: 'Serving boards, glassware, desk objects, and accents for curated living.',
  },
  {
    title: 'Exclusive Editions',
    slug: 'exclusive-editions',
    count: countByCategory('Exclusive Editions'),
    img: 'https://images.unsplash.com/photo-1604014237800-1c9102c219da?w=800&q=80',
    size: 'wide',
    description: 'Numbered, limited-run pieces for collectors who value rarity and craft.',
  },
]

export function getProductBySlug(slug: string): Product | undefined {
  return catalog.find((p) => p.slug === slug)
}

export function getRelatedProducts(product: Product, limit = 4): Product[] {
  return catalog
    .filter((p) => p.category === product.category && p.slug !== product.slug)
    .slice(0, limit)
}

export function getProductsByCategory(category: string): Product[] {
  return catalog.filter((p) => p.category === category)
}

export function parsePrice(price: string): number {
  return Number(price.replace(/[^0-9.]/g, ''))
}

export function getAllSlugs(): string[] {
  return catalog.map((p) => p.slug)
}
